@startuml
class MorseEntry {
 -morseCode: string
 -originalText: string
 +MorseEntry(morseCode : string, originalText : string)
 +getMorseCode():string
 +setMorseCode(string)
 +getOriginalText():string
 +setOriginalText(string)
 +toString(): void
 +hashCode() void
}
class MorseConverter{
+morseMap : List<HashMap>
+toMorse() : void
}
class FileManager{
-filename: string
+FileManager(filename : string)
+WriteEntries() : void
+ReadEntries() : void
}
MorseEntry "1" -- "1" MorseConverter
@enduml
