@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
class Rettangolo {
 -latoMaggiore: int
 -latoMinore: int
 +Rettangolo(latoMaggiore : int, latoMinore : int)
 +getLatoMaggiore(): int
 +setLatoMaggiore(int)
 +getLatoMinore(): int
 +setLatoMinore(int)
 +toString(string)
}
@enduml